export { REGEX, MESSAGES } from './rules';
export type { ValidationResult, ValidatorFn } from './validators';

export {
  validateRequired,
  validateRequiredSelect,
  validatePhone,
  validateMobile,
  validateLandline,
  validateEmail,
  validateIdCard,
  validateIdCard15,
  validateIdCard18,
  validateSocialCredit,
  validateMinLength,
  validateMaxLength,
  validateLength,
  validateExactLength,
  validateMin,
  validateMax,
  validateRange,
  validateNumber,
  validateInteger,
  validatePositiveNumber,
  validateNegativeNumber,
  validateDecimal,
  validatePositiveDecimal,
  validateNoWhitespace,
  validatePassword,
  validatePasswordWeak,
  validatePasswordConfirm,
  validatePasswordNotSame,
  validateChinese,
  validateChineseAndEnglish,
  validateEnglish,
  validateAlphanumeric,
  validateAlphanumericWithUnderscore,
  validateUrl,
  validateHttpUrl,
  validateIp,
  validatePostcode,
  validateQq,
  validateWechat,
  validateLicensePlate,
  validateBankCard,
  validateLongitude,
  validateLatitude,
  validateUsername,
  validateVersion,
  validatePattern,
  validateCustom,
  validateDateRange,
  validateTimeRange,
  validate,
  validateAll,
  getCharTypeCount,
  calculatePasswordSimilarity,
} from './validators';

import {
  validateRequired as vRequired,
  validateRequiredSelect as vRequiredSelect,
  validatePhone as vPhone,
  validateMobile as vMobile,
  validateLandline as vLandline,
  validateEmail as vEmail,
  validateIdCard as vIdCard,
  validateIdCard15 as vIdCard15,
  validateIdCard18 as vIdCard18,
  validateSocialCredit as vSocialCredit,
  validateMinLength as vMinLength,
  validateMaxLength as vMaxLength,
  validateLength as vLength,
  validateExactLength as vExactLength,
  validateMin as vMin,
  validateMax as vMax,
  validateRange as vRange,
  validateNumber as vNumber,
  validateInteger as vInteger,
  validatePositiveNumber as vPositiveNumber,
  validateNegativeNumber as vNegativeNumber,
  validateDecimal as vDecimal,
  validatePositiveDecimal as vPositiveDecimal,
  validateNoWhitespace as vNoWhitespace,
  validatePassword as vPassword,
  validatePasswordWeak as vPasswordWeak,
  validatePasswordConfirm as vPasswordConfirm,
  validatePasswordNotSame as vPasswordNotSame,
  validateChinese as vChinese,
  validateChineseAndEnglish as vChineseAndEnglish,
  validateEnglish as vEnglish,
  validateAlphanumeric as vAlphanumeric,
  validateAlphanumericWithUnderscore as vAlphanumericWithUnderscore,
  validateUrl as vUrl,
  validateHttpUrl as vHttpUrl,
  validateIp as vIp,
  validatePostcode as vPostcode,
  validateQq as vQq,
  validateWechat as vWechat,
  validateLicensePlate as vLicensePlate,
  validateBankCard as vBankCard,
  validateLongitude as vLongitude,
  validateLatitude as vLatitude,
  validateUsername as vUsername,
  validateVersion as vVersion,
  validatePattern as vPattern,
  validateCustom as vCustom,
  validateDateRange as vDateRange,
  validateTimeRange as vTimeRange,
  validateAll as vValidateAll,
  type ValidatorFn as VValidatorFn,
  type ValidationResult as VValidationResult,
} from './validators';

export const createValidator = {
  required: () => vRequired,
  requiredSelect: () => vRequiredSelect,
  phone: () => vPhone,
  mobile: () => vMobile,
  landline: () => vLandline,
  email: () => vEmail,
  idCard: () => vIdCard,
  idCard15: () => vIdCard15,
  idCard18: () => vIdCard18,
  socialCredit: () => vSocialCredit,
  minLength: (min: number) => (value: string) => vMinLength(value, min),
  maxLength: (max: number) => (value: string) => vMaxLength(value, max),
  length: (min: number, max: number) => (value: string) => vLength(value, min, max),
  exactLength: (length: number) => (value: string) => vExactLength(value, length),
  min: (min: number) => (value: number) => vMin(value, min),
  max: (max: number) => (value: number) => vMax(value, max),
  range: (min: number, max: number) => (value: number) => vRange(value, min, max),
  number: () => vNumber,
  integer: () => vInteger,
  positiveNumber: () => vPositiveNumber,
  negativeNumber: () => vNegativeNumber,
  decimal: () => vDecimal,
  positiveDecimal: () => vPositiveDecimal,
  noWhitespace: () => vNoWhitespace,
  password: (minTypeCount: number = 3) => (value: string) => vPassword(value, minTypeCount),
  passwordWeak: () => vPasswordWeak,
  passwordConfirm: (password: string) => (value: string) => vPasswordConfirm(password, value),
  passwordNotSame: (oldPassword: string, threshold: number = 0.6) => (value: string) =>
    vPasswordNotSame(oldPassword, value, threshold),
  chinese: () => vChinese,
  chineseAndEnglish: () => vChineseAndEnglish,
  english: () => vEnglish,
  alphanumeric: () => vAlphanumeric,
  alphanumericWithUnderscore: () => vAlphanumericWithUnderscore,
  url: () => vUrl,
  httpUrl: () => vHttpUrl,
  ip: () => vIp,
  postcode: () => vPostcode,
  qq: () => vQq,
  wechat: () => vWechat,
  licensePlate: () => vLicensePlate,
  bankCard: () => vBankCard,
  longitude: () => vLongitude,
  latitude: () => vLatitude,
  username: () => vUsername,
  version: () => vVersion,
  pattern: (regex: RegExp, message?: string) => (value: string) => vPattern(value, regex, message),
  custom: (fn: (value: any) => boolean, message?: string) => (value: any) => vCustom(value, fn, message),
  dateRange: (startDate: string) => (value: string) => vDateRange(startDate, value),
  timeRange: (startTime: string, startDate?: string, endDate?: string) => (value: string) =>
    vTimeRange(startTime, value, startDate, endDate),
};

export const validateForm = <T extends Record<string, any>>(
  formData: T,
  rules: Record<keyof T, VValidatorFn[]>
): { valid: boolean; errors: Partial<Record<keyof T, string>>; firstError?: string; firstErrorField?: string } => {
  const result = vValidateAll(formData, rules as Record<string, VValidatorFn[]>);
  return {
    valid: result.valid,
    errors: result.errors as Partial<Record<keyof T, string>>,
    firstError: result.firstError,
    firstErrorField: result.firstErrorField as keyof T | undefined,
  };
};

export const createFormRules = <T extends Record<string, any>>() => {
  return <K extends keyof T>(field: K, rules: VValidatorFn<T[K]>[]) => ({
    field,
    rules,
  });
};
