export const REGEX = {
  phone: /^1[3-9]\d{9}$/,
  email: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
  idCard: /(^\d{15}$)|(^\d{18}$)|(^\d{17}(\d|X|x)$)/,
  password: /^[a-zA-Z0-9!@#$%^&*(),.?":{}|<>_\-+=\[\]\\\/~`]{8,20}$/,
  passwordWeak: /^.{6,}$/,
  hasLowerCase: /[a-z]/,
  hasUpperCase: /[A-Z]/,
  hasNumber: /\d/,
  hasSpecialChar: /[!@#$%^&*(),.?":{}|<>_\-+=\[\]\\\/~`]/,
  hasWhitespace: /\s/,
  chinese: /^[\u4e00-\u9fa5]+$/,
  chineseAndEnglish: /^[\u4e00-\u9fa5a-zA-Z]+$/,
  chineseWithPunctuation: /^[\u4e00-\u9fa5，。、；：""''（）【】《》！？\s]+$/,
  english: /^[a-zA-Z]+$/,
  alphanumeric: /^[a-zA-Z0-9]+$/,
  alphanumericWithUnderscore: /^[a-zA-Z0-9_]+$/,
  number: /^\d+$/,
  integer: /^-?\d+$/,
  positiveNumber: /^[1-9]\d*$/,
  negativeNumber: /^-[1-9]\d*$/,
  decimal: /^\d+(\.\d+)?$/,
  negativeDecimal: /^-\d+(\.\d+)?$/,
  positiveDecimal: /^[1-9]\d*(\.\d+)?$|^0\.\d*[1-9]\d*$/,
  negativeDecimal: /^-[1-9]\d*(\.\d+)?$|^-0\.\d*[1-9]\d*$/,
  url: /^(https?:\/\/)?([\da-z.-]+)\.([a-z.]{2,6})([/\w .-]*)*\/?$/,
  httpUrl: /^https?:\/\/.+/,
  ip: /^((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$/,
  ipv6: /^([\da-fA-F]{1,4}:){7}[\da-fA-F]{1,4}$/,
  postcode: /^\d{6}$/,
  qq: /^[1-9]\d{4,10}$/,
  wechat: /^[a-zA-Z\d_-]{5,}$/,
  licensePlate: /^[京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领][A-Z][A-HJ-NP-Z0-9]{4,5}[A-HJ-NP-Z0-9挂学警港澳]$/,
  bankCard: /^\d{16,19}$/,
  longitude: /^-?((180(\.0+)?)|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)$/,
  latitude: /^-?((90(\.0+)?)|([1-8]?\d(\.\d+)?))$/,
  hexColor: /^#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$/,
  rgbColor: /^rgb\((\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\)$/,
  rgbaColor: /^rgba\((\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3}),\s*(0|1|0?\.\d+)\)$/,
  base64: /^data:[a-z]+\/[a-z0-9-+.]+;base64,/,
  emoji: /[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/u,
  username: /^[a-zA-Z][a-zA-Z0-9_]{2,15}$/,
  version: /^\d+(\.\d+){0,2}$/,
  chineseMobile: /^1[3-9]\d{9}$/,
  chineseLandline: /^0\d{2,3}-?\d{7,8}$/,
  chineseIdCard15: /^\d{15}$/,
  chineseIdCard18: /^\d{17}[\dXx]$/,
  chineseSocialCredit: /^[0-9A-HJ-NPQRTUWXY]{2}\d{6}[0-9A-HJ-NPQRTUWXY]{10}$/,
} as const;

export const MESSAGES = {
  required: '此项为必填项',
  requiredSelect: '请选择',
  requiredChoose: '请选择至少一项',
  phone: '请输入正确的手机号码',
  mobile: '请输入正确的手机号码',
  landline: '请输入正确的固定电话号码',
  email: '请输入正确的邮箱地址',
  idCard: '请输入正确的身份证号码',
  idCard15: '请输入正确的15位身份证号码',
  idCard18: '请输入正确的18位身份证号码',
  socialCredit: '请输入正确的统一社会信用代码',
  password: '密码长度需8-20位，包含字母、数字、特殊字符中至少3类',
  passwordWeak: '密码长度不能少于6位',
  passwordConfirm: '两次输入的密码不一致',
  passwordSameAsOld: '新密码不能与当前密码相同',
  passwordTooSimilar: '新密码与当前密码过于相似',
  passwordComplexity: '密码强度不足，请增加复杂度',
  minLength: (min: number) => `最少需要${min}个字符`,
  maxLength: (max: number) => `最多不能超过${max}个字符`,
  length: (min: number, max: number) => `长度需在${min}-${max}个字符之间`,
  exactLength: (length: number) => `必须是${length}个字符`,
  min: (min: number) => `不能小于${min}`,
  max: (max: number) => `不能大于${max}`,
  range: (min: number, max: number) => `需在${min}-${max}之间`,
  number: '请输入数字',
  integer: '请输入整数',
  positiveNumber: '请输入正整数',
  negativeNumber: '请输入负整数',
  decimal: '请输入数字',
  positiveDecimal: '请输入正数',
  negativeDecimal: '请输入负数',
  chinese: '请输入中文',
  chineseAndEnglish: '只能输入中文和英文',
  english: '请输入英文',
  alphanumeric: '只能输入字母和数字',
  alphanumericWithUnderscore: '只能输入字母、数字和下划线',
  url: '请输入正确的网址',
  httpUrl: '请输入以http://或https://开头的网址',
  noWhitespace: '不能包含空格',
  charTypeCount: (count: number) => `需包含大写字母、小写字母、数字、特殊字符中至少${count}类`,
  dateRange: '结束日期不能早于开始日期',
  timeRange: '结束时间不能早于开始时间',
  ip: '请输入正确的IP地址',
  ipv6: '请输入正确的IPv6地址',
  postcode: '请输入正确的邮政编码',
  qq: '请输入正确的QQ号码',
  wechat: '请输入正确的微信号',
  licensePlate: '请输入正确的车牌号',
  bankCard: '请输入正确的银行卡号',
  longitude: '请输入正确的经度（-180到180）',
  latitude: '请输入正确的纬度（-90到90）',
  hexColor: '请输入正确的十六进制颜色值',
  rgbColor: '请输入正确的RGB颜色值',
  rgbaColor: '请输入正确的RGBA颜色值',
  username: '用户名需以字母开头，长度3-16位，只能包含字母、数字和下划线',
  version: '请输入正确的版本号格式（如1.0.0）',
  pattern: '格式不正确',
  custom: '验证失败',
} as const;
